apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: tech-challenge
  labels:
    app: api
spec:
  selector:
    app: api
  type: LoadBalancer
  ports:
    - name: http
      port: 8080
      targetPort: 80
      protocol: TCP