version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:80"
    volumes:
      - .:/var/www/html
    environment:
      - APACHE_RUN_USER=#1000
      - APACHE_RUN_GROUP=#1000
  
  db:
    image: mysql:latest
    command: 
      - --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./tech-challange.sql:/docker-entrypoint-initdb.d/tech-challange.sql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
  
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1