apiVersion: v1
kind: Service
metadata:
  namespace: tech-challenge
  name: database-service
  labels:
    app: database
spec:
  type: NodePort
  selector:
    app: database
  ports:
    - name: "database"
      protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 30432