apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: tech-challenge
  name: mysql-pv-claim
  labels:
    app: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi